services:
  gateway:
    image: amazoncorretto:20-alpine-jdk
    volumes:
      - /target/gateway-0.0.1-SNAPSHOT.jar:/app/gateway.jar
    command: ["java", "-jar", "/app/gateway.jar"]
    ports:
      - "127.0.0.1:8181:8181"
    hostname: gateway-svc

